apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-ingress-rule
spec:
  rules:
  - http:
      paths:
      - path: /hello
        backend:
          serviceName: flask
          servicePort: {{ .Values.service.port }}
